name: twitter
description: A Twitter clone that I made for my Software Design and Testing course.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  intl: ^0.15.8
  uuid: ^2.0.2
  provider: ^3.1.0
  md2_tab_indicator: ^1.0.2
  outline_material_icons: ^0.1.0
  url_launcher: ^5.1.2
  image_picker: ^0.6.0+4
  file_picker: ^1.3.8
  video_player: ^0.10.2+1
  path_provider: ^1.3.0
  thumbnails: ^1.0.1
  timeago: ^2.0.19

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/images/icon-48.png
   - assets/images/icon-480.png
  fonts:
    - family: Edge
      fonts:
        - asset: assets/fonts/edge.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product-sans/regular.ttf
          weight: 400
        - asset: assets/fonts/product-sans/bold.ttf
          weight: 700
        - asset: assets/fonts/product-sans/bold-italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/product-sans/medium.ttf
          weight: 600
        - asset: assets/fonts/product-sans/medium-italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/product-sans/italic.ttf
          style: italic